//
// Optional: Seed a demo user for development/testing.
// Usage:
//   mongosh "$MONGODB_URL/$MONGODB_DB" --file seed_demo_user.js
//
(function () {
  const email = "demo@example.com";
  const now = new Date();

  const users = db.getCollection("users");
  const existing = users.findOne({ email });
  if (existing) {
    print(`• Demo user '${email}' already exists (id: ${existing._id})`);
    return;
  }

  // IMPORTANT: passwordHash should be generated by backend (e.g., bcrypt/argon2).
  // For demo purposes only, store a placeholder hash.
  const demoHash = "$2b$12$demoHashReplaceWithRealHashFromBackendXXXXXXXXXXXXXX";

  const doc = {
    email,
    username: "demo",
    passwordHash: demoHash,
    oauthProvider: null,
    oauthProviderId: null,
    emailVerified: true,
    onboarding: {
      currentStep: 1,
      completedSteps: ["account"],
      startedAt: now,
      completedAt: null,
    },
    profile: {
      firstName: "Demo",
      lastName: "User",
      timezone: "UTC",
      marketingOptIn: false,
    },
    createdAt: now,
    updatedAt: now,
    lastLoginAt: null,
  };

  const res = users.insertOne(doc);
  print(`✓ Created demo user '${email}' with _id=${res.insertedId}`);
})();
